import type { Contact, Conversation, FollowUp } from '@/types'

export const mockContacts: Contact[] = [
  {
    id: 'contact-sarra-mansour',
    name: 'Sarra Mansour',
    phone: '+216 20 123 456',
    initials: 'SM',
    totalConversations: 3,
    tags: ['VIP', 'Site web'],
    notes: 'Demande souvent des confirmations rapides avant midi.',
    lastSeen: 'Aujourd’hui à 09:42',
  },
  {
    id: 'contact-karim-belhaj',
    name: 'Karim Belhaj',
    phone: '+216 98 765 432',
    initials: 'KB',
    totalConversations: 2,
    tags: ['Devis', 'B2B'],
    notes: 'Compare les offres avant de décider.',
    lastSeen: 'Hier à 18:10',
  },
  {
    id: 'contact-leila-trabelsi',
    name: 'Leila Trabelsi',
    phone: '+216 25 444 888',
    initials: 'LT',
    totalConversations: 1,
    tags: ['Rendez-vous'],
    notes: 'Préférence pour les créneaux du matin.',
    lastSeen: 'Aujourd’hui à 08:57',
  },
  {
    id: 'contact-ahmed-sfar',
    name: 'Ahmed Sfar',
    phone: '+216 21 332 119',
    initials: 'AS',
    totalConversations: 4,
    tags: ['Réclamation', 'Urgent'],
    notes: 'Attentif au suivi et aux délais.',
    lastSeen: 'Il y a 32 min',
  },
  {
    id: 'contact-nour-jebali',
    name: 'Nour Jebali',
    phone: '+216 22 909 101',
    initials: 'NJ',
    totalConversations: 2,
    tags: ['Commande', 'WhatsApp'],
    notes: 'Pose des questions sur la livraison et le stock.',
    lastSeen: 'Hier à 20:14',
  },
  {
    id: 'contact-rym-chaabane',
    name: 'Rym Chaabane',
    phone: '+216 27 555 013',
    initials: 'RC',
    totalConversations: 1,
    tags: ['Suivi'],
    notes: 'Répond rapidement pendant la pause déjeuner.',
    lastSeen: 'Aujourd’hui à 12:06',
  },
  {
    id: 'contact-youssef-mrad',
    name: 'Youssef Mrad',
    phone: '+216 29 888 204',
    initials: 'YM',
    totalConversations: 2,
    tags: ['Budget', 'Appel'],
    notes: 'Veut un rappel avant de valider.',
    lastSeen: 'Lundi à 16:40',
  },
  {
    id: 'contact-ines-bouaziz',
    name: 'Ines Bouaziz',
    phone: '+216 24 606 707',
    initials: 'IB',
    totalConversations: 3,
    tags: ['Autre', 'Nouveau'],
    notes: 'Intéressée par un accompagnement personnalisé.',
    lastSeen: 'Aujourd’hui à 10:18',
  },
]

export const mockConversations: Conversation[] = [
  {
    id: 'conv-sarra-mansour',
    contact: mockContacts[0],
    status: 'NEW',
    intent: 'RDV',
    lastMessage: 'Nheb nchouf les disponibilités pour demain matin, s’il vous plaît.',
    time: '09:42',
    unread: true,
    messages: [
      {
        id: 'msg-sarra-1',
        content: 'Bonjour, je veux réserver un créneau pour demain matin.',
        direction: 'INBOUND',
        timestamp: '2026-06-14T08:58:00+02:00',
      },
      {
        id: 'msg-sarra-2',
        content: 'Bonjour Sarra, avec plaisir. Vous préférez 9h ou 10h ?',
        direction: 'OUTBOUND',
        timestamp: '2026-06-14T09:00:00+02:00',
      },
      {
        id: 'msg-sarra-3',
        content: '9h serait parfait, inchallah.',
        direction: 'INBOUND',
        timestamp: '2026-06-14T09:03:00+02:00',
      },
      {
        id: 'msg-sarra-4',
        content: 'Parfait, je vous confirme le rendez-vous à 9h demain matin.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-14T09:05:00+02:00',
      },
    ],
    summary: 'Demande de rendez-vous tôt le matin, confirmation en attente.',
  },
  {
    id: 'conv-karim-belhaj',
    contact: mockContacts[1],
    status: 'IN_PROGRESS',
    intent: 'PRIX',
    lastMessage: 'Tu peux m’envoyer une offre détaillée avec les options ?',
    time: 'Hier',
    unread: false,
    messages: [
      {
        id: 'msg-karim-1',
        content: 'Salem, vous avez un tarif pour une prestation mensuelle ?',
        direction: 'INBOUND',
        timestamp: '2026-06-13T17:20:00+02:00',
      },
      {
        id: 'msg-karim-2',
        content: 'Oui, on a plusieurs formules selon le volume de demandes.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-13T17:24:00+02:00',
      },
      {
        id: 'msg-karim-3',
        content: 'Béhi, j’ai besoin surtout du coût pour 3 utilisateurs.',
        direction: 'INBOUND',
        timestamp: '2026-06-13T17:31:00+02:00',
      },
      {
        id: 'msg-karim-4',
        content: 'Je vous prépare une offre détaillée avec les options et les remises.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-13T17:36:00+02:00',
      },
    ],
    needsFollowUp: true,
    followUpAt: '2026-06-16T11:00:00+02:00',
    summary: 'Comparaison de prix en cours, offre personnalisée à envoyer.',
  },
  {
    id: 'conv-leila-trabelsi',
    contact: mockContacts[2],
    status: 'CONFIRMED',
    intent: 'RDV',
    lastMessage: 'Merci, je serai là à 10h pile.',
    time: '08:57',
    unread: false,
    messages: [
      {
        id: 'msg-leila-1',
        content: 'Bonjour, est-ce qu’il reste un créneau jeudi matin ?',
        direction: 'INBOUND',
        timestamp: '2026-06-14T08:05:00+02:00',
      },
      {
        id: 'msg-leila-2',
        content: 'Oui, nous avons encore 10h et 10h30 disponibles.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-14T08:08:00+02:00',
      },
      {
        id: 'msg-leila-3',
        content: 'Top, je prends 10h, c’est possible ?',
        direction: 'INBOUND',
        timestamp: '2026-06-14T08:12:00+02:00',
      },
      {
        id: 'msg-leila-4',
        content: 'Oui, c’est confirmé pour jeudi à 10h.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-14T08:14:00+02:00',
      },
    ],
    summary: 'Rendez-vous confirmé pour jeudi 10h.',
  },
  {
    id: 'conv-ahmed-sfar',
    contact: mockContacts[3],
    status: 'FOLLOW_UP',
    intent: 'RÉCLAMATION',
    lastMessage: 'J’attends toujours le retour, c’est un peu urgent.',
    time: 'Il y a 32 min',
    unread: true,
    messages: [
      {
        id: 'msg-ahmed-1',
        content: 'Salem, j’ai un souci avec la dernière commande.',
        direction: 'INBOUND',
        timestamp: '2026-06-14T11:05:00+02:00',
      },
      {
        id: 'msg-ahmed-2',
        content: 'Je suis désolé pour ça, je regarde le dossier tout de suite.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-14T11:07:00+02:00',
      },
      {
        id: 'msg-ahmed-3',
        content: 'Merci, mais je n’ai pas encore eu de réponse concrète.',
        direction: 'INBOUND',
        timestamp: '2026-06-14T11:18:00+02:00',
      },
      {
        id: 'msg-ahmed-4',
        content: 'Je fais le nécessaire et je vous recontacte dans la journée.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-14T11:21:00+02:00',
      },
    ],
    needsFollowUp: true,
    followUpAt: '2026-06-12T16:30:00+02:00',
    summary: 'Réclamation client prioritaire avec suivi à relancer.',
  },
  {
    id: 'conv-nour-jebali',
    contact: mockContacts[4],
    status: 'RESOLVED',
    intent: 'COMMANDE',
    lastMessage: 'Le colis est bien arrivé, merci khouya.',
    time: 'Hier',
    unread: false,
    messages: [
      {
        id: 'msg-nour-1',
        content: 'Bonjour, la commande est-elle partie aujourd’hui ?',
        direction: 'INBOUND',
        timestamp: '2026-06-13T14:10:00+02:00',
      },
      {
        id: 'msg-nour-2',
        content: 'Oui, elle a été expédiée ce matin avec suivi.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-13T14:13:00+02:00',
      },
      {
        id: 'msg-nour-3',
        content: 'Super, tbarakallah. Vous me partagez le numéro ?',
        direction: 'INBOUND',
        timestamp: '2026-06-13T14:17:00+02:00',
      },
      {
        id: 'msg-nour-4',
        content: 'Bien sûr, voici le lien de suivi et le numéro du colis.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-13T14:20:00+02:00',
      },
    ],
    summary: 'Commande expédiée et suivie, conversation résolue.',
  },
  {
    id: 'conv-rym-chaabane',
    contact: mockContacts[5],
    status: 'FOLLOW_UP',
    intent: 'AUTRE',
    lastMessage: 'Quand est-ce que vous pouvez me rappeler ?',
    time: '12:06',
    unread: true,
    messages: [
      {
        id: 'msg-rym-1',
        content: 'Bonjour, j’ai vu votre service sur Instagram.',
        direction: 'INBOUND',
        timestamp: '2026-06-14T11:40:00+02:00',
      },
      {
        id: 'msg-rym-2',
        content: 'Merci Rym, ravis de votre intérêt. Je peux vous aider ?',
        direction: 'OUTBOUND',
        timestamp: '2026-06-14T11:42:00+02:00',
      },
      {
        id: 'msg-rym-3',
        content: 'Oui, juste besoin de quelques infos avant de décider.',
        direction: 'INBOUND',
        timestamp: '2026-06-14T11:49:00+02:00',
      },
      {
        id: 'msg-rym-4',
        content: 'Pas de souci, je vous rappelle dans l’après-midi, inchallah.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-14T11:52:00+02:00',
      },
    ],
    needsFollowUp: true,
    followUpAt: '2026-06-14T15:00:00+02:00',
    summary: 'Demande d’informations générales, rappel prévu aujourd’hui.',
  },
  {
    id: 'conv-youssef-mrad',
    contact: mockContacts[6],
    status: 'IN_PROGRESS',
    intent: 'PRIX',
    lastMessage: 'Si le budget reste sous 5000 TND, je suis chaud.',
    time: 'Lundi',
    unread: false,
    messages: [
      {
        id: 'msg-youssef-1',
        content: 'Salut, vous avez une idée du budget minimum ?',
        direction: 'INBOUND',
        timestamp: '2026-06-09T16:10:00+02:00',
      },
      {
        id: 'msg-youssef-2',
        content: 'Oui, on peut démarrer avec une formule adaptée à votre volume.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-09T16:13:00+02:00',
      },
      {
        id: 'msg-youssef-3',
        content: 'Bahi, j’aimerais rester sur quelque chose de simple.',
        direction: 'INBOUND',
        timestamp: '2026-06-09T16:18:00+02:00',
      },
      {
        id: 'msg-youssef-4',
        content: 'Je vous envoie une proposition claire avec le détail du budget.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-09T16:22:00+02:00',
      },
    ],
    needsFollowUp: true,
    followUpAt: '2026-06-18T10:30:00+02:00',
    summary: 'Demande de prix simple, relance à faire cette semaine.',
  },
  {
    id: 'conv-ines-bouaziz',
    contact: mockContacts[7],
    status: 'CONFIRMED',
    intent: 'COMMANDE',
    lastMessage: 'Parfait, on valide la commande aujourd’hui.',
    time: '10:18',
    unread: false,
    messages: [
      {
        id: 'msg-ines-1',
        content: 'Bonjour, je voudrais revoir les détails avant de valider.',
        direction: 'INBOUND',
        timestamp: '2026-06-14T09:50:00+02:00',
      },
      {
        id: 'msg-ines-2',
        content: 'Bien sûr, je vous renvoie le récap complet tout de suite.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-14T09:53:00+02:00',
      },
      {
        id: 'msg-ines-3',
        content: 'Merci, j’attends juste la dernière validation.',
        direction: 'INBOUND',
        timestamp: '2026-06-14T10:05:00+02:00',
      },
      {
        id: 'msg-ines-4',
        content: 'C’est bon, tout est prêt pour validation finale.',
        direction: 'OUTBOUND',
        timestamp: '2026-06-14T10:08:00+02:00',
      },
    ],
    summary: 'Commande en attente de validation finale.',
  },
]

export const mockFollowUps: FollowUp[] = [
  {
    id: 'followup-ahmed',
    contact: mockContacts[3],
    intent: 'RÉCLAMATION',
    followUpAt: '2026-06-12T16:30:00+02:00',
    overdue: true,
  },
  {
    id: 'followup-karim',
    contact: mockContacts[1],
    intent: 'PRIX',
    followUpAt: '2026-06-13T11:00:00+02:00',
    overdue: true,
  },
  {
    id: 'followup-rym',
    contact: mockContacts[5],
    intent: 'AUTRE',
    followUpAt: '2026-06-14T15:00:00+02:00',
    overdue: false,
  },
  {
    id: 'followup-youssef',
    contact: mockContacts[6],
    intent: 'PRIX',
    followUpAt: '2026-06-16T10:30:00+02:00',
    overdue: false,
  },
  {
    id: 'followup-sarra',
    contact: mockContacts[0],
    intent: 'RDV',
    followUpAt: '2026-06-18T09:00:00+02:00',
    overdue: false,
  },
]
